// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZL6twLZNevaUb_ANJ44Y5f6x6gvs3V7I',
    appId: '1:867792316898:android:be79320d9260686ea771bb',
    messagingSenderId: '867792316898',
    projectId: 'ashesicom',
    storageBucket: 'ashesicom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADbZ30Zm8BGtv-BhS1bxzK56jW6POkmz8',
    appId: '1:867792316898:ios:1d420feee58ce669a771bb',
    messagingSenderId: '867792316898',
    projectId: 'ashesicom',
    storageBucket: 'ashesicom.appspot.com',
    iosClientId: '867792316898-pjdpl7p2aitc3rdie51aoubdc75tuj4o.apps.googleusercontent.com',
    iosBundleId: 'com.example.ashesiCom',
  );
}
